name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.4"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacheck
          luarocks install luacov
          luarocks install \
            --server=https://luarocks.org/manifests/britzl \
            luacov-cobertura 1.1-0

      - name: Run CI
        run: bash ./scripts/ci.sh
